name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: RepoCheckout
      uses: actions/checkout@v4
  
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.6.3'
        host: 'linux'
        target: 'desktop'
  
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake
  
    - name: Configure CMake
      run: cmake -S ./client -B build -DCMAKE_PREFIX_PATH=$HOME/Qt/6.6.3/gcc_64
  
    - name: Build client
      run: cmake --build build --config Release

    - name: Build server
      run: g++ ./server/server.cpp -o server

    - name: Upload client artefact
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: build/
        
    - name: Upload server artefact
      uses: actions/upload-artefact@v4
      with:
        name: server
        path: server/
